### ISSUE TITLE
Create High-Level Class Diagram for Application Architecture (2)

### ISSUE THREAD

**Issue by jhonatansossa** [jhonatansossa/SmartRoomData#3]
**Priority:**

**Estimate:**

**Description:**
As a development team, we need to create a high-level class diagram that provides an overview of the application's architecture, including its three layers (frontend, backend, and perception) and interactions with two databases. This high-level class diagram will serve as a simplified visual reference for the system's structure and interactions to guide our development process effectively.

**Acceptance Criteria:**
1. The high-level class diagram should provide a simplified, top-down representation of the three layers of the application: frontend, backend, and persistence.

2. The diagram should illustrate the primary classes and components within each layer to give a general sense of their functionality and interactions.

3. Class and component names should be included on the diagram to provide a basic understanding of what each element represents within the layers.

4. The high-level class diagram should adhere to common modeling notations to ensure clarity, but it does not need to be overly detailed.

5. Suggested classes/components for the high-level diagram:

  - Frontend Layer: UI Components, Controllers, APIs.
  - Backend Layer: Application Logic, Services, Data Access.
  - Perception Layer: Items, Database Entities and Data Access.
 
6. The class diagram should be created using a suitable modeling tool (e.g., UML modeling software).

7. The diagram should be reviewed by the development team to ensure its alignment with the high-level architecture and design of the application.

8. The acceptance criteria for this user story will be considered met when the high-level class diagram is finalized, approved by the development team, and ready for use as a simplified reference during the application development and initial planning stages.

**Comment by NotDhalix** [comment]
The class diagram is not clear and does not work.
