### ISSUE TITLE
Define Tools and Versions for Each Application Layer (2)

### ISSUE THREAD

**Issue by jhonatansossa** [jhonatansossa/SmartRoomData#7]
**Priority:**

**Estimation:**

**Description:**
As a development team, we need to specify the tools and their corresponding versions to be used in each of the three application layers (frontend, backend, and perception) as well as for the two databases. This ensures consistency, compatibility, and a well-defined development environment.

**Acceptance Criteria:**
1. Identify and document the tools and their versions for each application layer as follows:

-   Frontend Layer:

-     Specify the programming languages, frameworks, and libraries. For example: HTML5, CSS3, JavaScript (ES6), React 17.0.2.

-   Backend Layer:

-     Specify the programming languages, frameworks, and libraries. For example: Python 3.9, Flask 2.0.1, Django 4.0.0.

-   Perception Layer:

-     Specify the database management systems and relevant technologies. For example: OpenHab 3.0.2.

-   Database Layer:

-     Specify the database management systems and versions. For example: MySQL 8.0.2, Redis 6.2.1.

2. Ensure that the selected tools and their versions are well-documented and communicated to the development team. This documentation should be accessible to all team members.

3. Verify that the chosen tools and versions are compatible with each other within and across layers, addressing any potential conflicts or dependencies.

4. Review and validate the tool choices and versions with the development team and stakeholders to ensure they align with the project's technical objectives and constraints.

5. The acceptance criteria for this user story will be considered met when the tools and their versions are clearly defined and documented for each application layer and database layer, and they are confirmed to be compatible and in use.

**Comment by shaheryar1** [comment]
Done for Data Analytics server.

**Comment by jhonatansossa** [comment]
Done for Backend and perception layers
